export const TIPS = [
  {
    number: "01", icon: "💬", title: "Xatolardan qo'rqma",
    short: "Xato qilish — o'rganishning bir qismi. Gapira boshlash eng muhimi!",
    detail: "Har bir so'zni mukammal talaffuz qilishga harakat qilma. Asosiysi — gapirish! 'Ich gehen morgen in der Markt' desang ham — tushuniladi. Vaqt o'tishi bilan o'z-o'zidan to'g'rilanadi."
  },
  {
    number: "02", icon: "📚", title: "Mustahkam asos yasat",
    short: "Asosiy so'zlar va grammatikani o'rgan — der/die/das, fe'llar, olmoshlar.",
    detail: "Barcha tartibsiz fe'llarni yod olishning hojati yo'q. Muhim narsalar: artiklar, olmoshlar, hozirgi zamon fe'llari, modal fe'llar va oddiy gap qurilishi."
  },
  {
    number: "03", icon: "🎧", title: "Tinglash va taqlid qil",
    short: "Podcast, video, qo'shiq tinglash — so'ng eshitganingni takrorla.",
    detail: "Gapni to'xtatib, baland ovozda takrorla. Ritm, urg'u va talaffuzni taqlid qil. Musiqa o'rganishga o'xshaydi — ko'p eshitsang, grammatikani bilmasdan ham aytib bera olasan."
  },
  {
    number: "04", icon: "🗣️", title: "Baland ovozda mashq qil",
    short: "Uyda yolg'iz bo'lsang ham — nemischa gapir! O'zingga gapir.",
    detail: "Ko'rayotganing, qilayotganing haqida nemischa gapir. O'zingni yozib ol va tinglang — qayerda qiynalayotganingni tezda payqaysan."
  },
  {
    number: "05", icon: "📱", title: "Nemischani kundalik hayotga kirit",
    short: "Telefon tilini nemischaga o'zgar, nemis video/musiqa ko'r.",
    detail: "Ertalab — nemischa YouTube. Yo'lda — podcast. Kechqurun — bolalar kitobini o'qi. Xarid ro'yxatini nemischa yoz. Nemischa 'fan' emas, hayotning bir qismi bo'lsin!"
  },
];

export const VOCAB = {
  Verben: [
    { de: "sein", uz: "bo'lmoq" }, { de: "haben", uz: "ega bo'lmoq" }, { de: "werden", uz: "bo'lmoq (kelajak)" },
    { de: "können", uz: "qila olmoq" }, { de: "müssen", uz: "kerak bo'lmoq" }, { de: "wollen", uz: "xohlamoq" },
    { de: "dürfen", uz: "ruxsat bo'lmoq" }, { de: "machen", uz: "qilmoq" }, { de: "sagen", uz: "aytmoq" },
    { de: "gehen", uz: "bormoq / yurmoq" }, { de: "kommen", uz: "kelmoq" }, { de: "geben", uz: "bermoq" },
    { de: "sehen", uz: "ko'rmoq" }, { de: "stehen", uz: "turmoq" }, { de: "finden", uz: "topmoq" },
    { de: "bleiben", uz: "qolmoq" }, { de: "liegen", uz: "yotmoq" }, { de: "nehmen", uz: "olmoq" },
    { de: "wissen", uz: "bilmoq" }, { de: "leben", uz: "yashmoq" }, { de: "bringen", uz: "olib kelmoq" },
    { de: "essen", uz: "yemoq" }, { de: "trinken", uz: "ichmoq" }, { de: "sprechen", uz: "gapirmoq" },
    { de: "schreiben", uz: "yozmoq" }, { de: "lesen", uz: "o'qimoq" }, { de: "fahren", uz: "haydamoq / bormoq" },
    { de: "kaufen", uz: "sotib olmoq" }, { de: "helfen", uz: "yordam bermoq" }, { de: "lernen", uz: "o'rganmoq" },
    { de: "fragen", uz: "so'ramoq" }, { de: "antworten", uz: "javob bermoq" }, { de: "spielen", uz: "o'ynamoq" },
    { de: "arbeiten", uz: "ishlashmoq" }, { de: "denken", uz: "o'ylamoq" }, { de: "glauben", uz: "ishonmoq" },
    { de: "brauchen", uz: "kerak bo'lmoq" }, { de: "suchen", uz: "qidirmoq" }, { de: "zeigen", uz: "ko'rsatmoq" },
    { de: "versuchen", uz: "urinmoq" }, { de: "tragen", uz: "ko'tarmoq / kiymoq" }, { de: "halten", uz: "ushlamoq" },
    { de: "öffnen", uz: "ochmoq" }, { de: "schließen", uz: "yopmoq" }, { de: "beginnen", uz: "boshlamoq" },
    { de: "enden", uz: "tugamoq" }, { de: "laufen", uz: "yugurmoq" }, { de: "sitzen", uz: "o'tirmoq" },
    { de: "schlafen", uz: "uxlamoq" }, { de: "wohnen", uz: "yashmoq (turmoq)" }, { de: "heißen", uz: "atalmoq / ismim" },
    { de: "bekommen", uz: "olmoq / qabul qilmoq" }, { de: "verlieren", uz: "yo'qotmoq" }, { de: "gewinnen", uz: "yutmoq" },
    { de: "fühlen", uz: "his qilmoq" }, { de: "treffen", uz: "uchrashmoq" }, { de: "kennen", uz: "tanish bo'lmoq" },
    { de: "hören", uz: "eshitmoq" }, { de: "erklären", uz: "tushuntirmoq" }, { de: "feiern", uz: "nishonlamoq" },
    { de: "vergessen", uz: "unutmoq" }, { de: "erinnern", uz: "eslamoq" }, { de: "bedeuten", uz: "anglatmoq" },
    { de: "zahlen", uz: "to'lamoq" }, { de: "schicken", uz: "yubormoq" }, { de: "bestellen", uz: "buyurtma bermoq" },
    { de: "kochen", uz: "pishirmoq" }, { de: "backen", uz: "non/tort pishirmoq" }, { de: "tanzen", uz: "raqsga tushmoq" },
    { de: "malen", uz: "rasm chizmoq" }, { de: "reparieren", uz: "ta'mirlashmoq" }, { de: "wechseln", uz: "almashtirmoq" },
  ],
  Nomen: [
    { de: "der Mensch", uz: "inson" }, { de: "die Frau", uz: "ayol" }, { de: "der Mann", uz: "erkak" },
    { de: "das Kind", uz: "bola" }, { de: "das Haus", uz: "uy" }, { de: "die Wohnung", uz: "kvartira" },
    { de: "das Zimmer", uz: "xona" }, { de: "die Tür", uz: "eshik" }, { de: "das Fenster", uz: "deraza" },
    { de: "der Tisch", uz: "stol" }, { de: "der Stuhl", uz: "stul" }, { de: "das Bett", uz: "karavot" },
    { de: "das Sofa", uz: "divan" }, { de: "der Schrank", uz: "shkaf" }, { de: "die Küche", uz: "oshxona" },
    { de: "das Bad", uz: "hammom" }, { de: "der Garten", uz: "bog'" }, { de: "die Straße", uz: "ko'cha" },
    { de: "der Weg", uz: "yo'l" }, { de: "die Stadt", uz: "shahar" }, { de: "das Dorf", uz: "qishloq" },
    { de: "das Auto", uz: "mashina" }, { de: "der Bus", uz: "avtobus" }, { de: "der Zug", uz: "poyezd" },
    { de: "das Fahrrad", uz: "velosiped" }, { de: "das Essen", uz: "ovqat" }, { de: "das Brot", uz: "non" },
    { de: "das Water", uz: "suv" }, { de: "der Kaffee", uz: "qahva" }, { de: "der Tee", uz: "choy" },
    { de: "das Fleisch", uz: "go'sht" }, { de: "das Gemüse", uz: "sabzavot" }, { de: "das Obst", uz: "meva" },
    { de: "der Apfel", uz: "olma" }, { de: "die Banane", uz: "banan" }, { de: "die Kartoffel", uz: "kartoshka" },
    { de: "der Reis", uz: "guruch" }, { de: "die Nudeln", uz: "makaron" }, { de: "die Milch", uz: "sut" },
    { de: "der Käse", uz: "pishloq" }, { de: "das Ei", uz: "tuxum" }, { de: "die Arbeit", uz: "ish" },
    { de: "die Schule", uz: "maktab" }, { de: "die Universität", uz: "universitet" }, { de: "der Lehrer", uz: "o'qituvchi" },
    { de: "der Schüler", uz: "o'quvchi" }, { de: "die Sprache", uz: "til" }, { de: "das Wort", uz: "so'z" },
    { de: "der Satz", uz: "gap / jumla" }, { de: "das Buch", uz: "kitob" }, { de: "die Zeitung", uz: "gazeta" },
    { de: "der Brief", uz: "xat" }, { de: "der Computer", uz: "kompyuter" }, { de: "das Telefon", uz: "telefon" },
    { de: "die Zeit", uz: "vaqt" }, { de: "der Tag", uz: "kun" }, { de: "die Nacht", uz: "tun" },
    { de: "der Morgen", uz: "ertalab" }, { de: "der Abend", uz: "kechqurun" }, { de: "der Nachmittag", uz: "tushdan keyin" },
    { de: "das Geld", uz: "pul" }, { de: "der Preis", uz: "narx" }, { de: "die Hilfe", uz: "yordam" },
    { de: "das Problem", uz: "muammo" }, { de: "der Fehler", uz: "xato" }, { de: "der Name", uz: "ism" },
    { de: "der Geburtstag", uz: "tug'ilgan kun" }, { de: "der Freund", uz: "do'st (erkak)" }, { de: "die Freundin", uz: "do'st (ayol)" },
    { de: "die Familie", uz: "oila" }, { de: "der Vater", uz: "ota" }, { de: "die Mutter", uz: "ona" },
    { de: "der Bruder", uz: "aka / uka" }, { de: "die Schwester", uz: "opa / singil" }, { de: "der Sohn", uz: "o'g'il" },
    { de: "die Tochter", uz: "qiz (farzand)" }, { de: "der Hund", uz: "it" }, { de: "die Katze", uz: "mushuk" },
    { de: "das Wetter", uz: "ob-havo" }, { de: "die Sonne", uz: "quyosh" }, { de: "der Regen", uz: "yomg'ir" },
    { de: "der Schnee", uz: "qor" }, { de: "der Wind", uz: "shamol" }, { de: "der Baum", uz: "daraxt" },
    { de: "die Blume", uz: "gul" }, { de: "der Berg", uz: "tog'" }, { de: "der See", uz: "ko'l" },
    { de: "der Fluss", uz: "daryo" }, { de: "das Land", uz: "mamlakat" }, { de: "die Musik", uz: "musiqa" },
    { de: "das Lied", uz: "qo'shiq" }, { de: "der Film", uz: "film" }, { de: "das Jahr", uz: "yil" },
    { de: "der Monat", uz: "oy" }, { de: "die Woche", uz: "hafta" }, { de: "die Minute", uz: "daqiqa" },
  ],
  Adjektive: [
    { de: "gut", uz: "yaxshi" }, { de: "schlecht", uz: "yomon" }, { de: "groß", uz: "katta" },
    { de: "klein", uz: "kichik" }, { de: "lang", uz: "uzun" }, { de: "kurz", uz: "qisqa" },
    { de: "schön", uz: "chiroyli" }, { de: "hässlich", uz: "xunuk" }, { de: "neu", uz: "yangi" },
    { de: "alt", uz: "eski / keksa" }, { de: "kalt", uz: "sovuq" }, { de: "warm", uz: "iliq" },
    { de: "heiß", uz: "issiq" }, { de: "teuer", uz: "qimmat" }, { de: "billig", uz: "arzon" },
    { de: "schnell", uz: "tez" }, { de: "langsam", uz: "sekin" }, { de: "leicht", uz: "oson / yengil" },
    { de: "schwer", uz: "og'ir / qiyin" }, { de: "laut", uz: "baland (ovoz)" }, { de: "leise", uz: "past (ovoz)" },
    { de: "hell", uz: "yorqin" }, { de: "dunkel", uz: "qorong'i" }, { de: "richtig", uz: "to'g'ri" },
    { de: "falsch", uz: "noto'g'ri" }, { de: "voll", uz: "to'la" }, { de: "leer", uz: "bo'sh" },
    { de: "nah", uz: "yaqin" }, { de: "fern", uz: "uzoq" }, { de: "jung", uz: "yosh" },
    { de: "modern", uz: "zamonaviy" }, { de: "dick", uz: "yo'g'on / semiz" }, { de: "dünn", uz: "ingichka / ozg'in" },
    { de: "breit", uz: "keng" }, { de: "eng", uz: "tor" }, { de: "tief", uz: "chuqur" },
    { de: "hoch", uz: "baland" }, { de: "sauber", uz: "toza" }, { de: "schmutzig", uz: "iflos" },
    { de: "süß", uz: "shirin" }, { de: "sauer", uz: "nordon" }, { de: "bitter", uz: "achchiq" },
    { de: "frisch", uz: "yangi / fresh" }, { de: "nass", uz: "ho'l" }, { de: "trocken", uz: "quruq" },
    { de: "rund", uz: "yumaloq" }, { de: "eckig", uz: "burchakli" }, { de: "lecker", uz: "mazali" },
    { de: "bekannt", uz: "mashhur / tanish" }, { de: "bequem", uz: "qulay" }, { de: "freundlich", uz: "do'stona" },
    { de: "froh", uz: "xursand" }, { de: "traurig", uz: "g'amgin" }, { de: "wichtig", uz: "muhim" },
    { de: "einfach", uz: "oddiy / oson" }, { de: "schwierig", uz: "qiyin" }, { de: "müde", uz: "charchagan" },
    { de: "wach", uz: "uyg'oq" }, { de: "nett", uz: "yoqimli" }, { de: "böse", uz: "yomon / g'azablangan" },
    { de: "interessant", uz: "qiziqarli" }, { de: "langweilig", uz: "zerikarli" }, { de: "spannend", uz: "hayajonli" },
    { de: "möglich", uz: "mumkin" }, { de: "unmöglich", uz: "mumkin emas" }, { de: "gesund", uz: "sog'lom" },
    { de: "krank", uz: "kasal" }, { de: "reich", uz: "boy" }, { de: "arm", uz: "kambag'al" },
    { de: "klar", uz: "aniq" }, { de: "lustig", uz: "kulgili" }, { de: "ernst", uz: "jiddiy" },
    { de: "vorsichtig", uz: "ehtiyotkor" }, { de: "gefährlich", uz: "xavfli" }, { de: "sicher", uz: "xavfsiz" },
    { de: "stark", uz: "kuchli" }, { de: "schwach", uz: "kuchsiz" }, { de: "kühl", uz: "salqin" },
    { de: "glatt", uz: "silliq" }, { de: "direkt", uz: "to'g'ridan-to'g'ri" }, { de: "pünktlich", uz: "o'z vaqtida" },
    { de: "spät", uz: "kech" }, { de: "früh", uz: "erta" }, { de: "schmal", uz: "tor" },
    { de: "clever", uz: "aqlli" }, { de: "dumm", uz: "ahmoq" }, { de: "fest", uz: "qattiq" },
    { de: "weich", uz: "yumshoq" }, { de: "scharf", uz: "o'tkir" }, { de: "normal", uz: "oddiy / normal" },
  ],
  Adverbien: [
    { de: "jetzt", uz: "hozir" }, { de: "hier", uz: "bu yerda" }, { de: "dort", uz: "u yerda" },
    { de: "heute", uz: "bugun" }, { de: "morgen", uz: "ertaga" }, { de: "gestern", uz: "kecha" },
    { de: "immer", uz: "doimo" }, { de: "nie", uz: "hech qachon" }, { de: "oft", uz: "ko'pincha" },
    { de: "selten", uz: "kamdan-kam" }, { de: "manchmal", uz: "ba'zan" }, { de: "vielleicht", uz: "ehtimol" },
    { de: "leider", uz: "afsuski" }, { de: "gern", uz: "mamnuniyat bilan" }, { de: "sehr", uz: "juda" },
    { de: "auch", uz: "ham" }, { de: "schon", uz: "allaqachon" }, { de: "noch", uz: "hali" },
    { de: "dann", uz: "keyin" }, { de: "danach", uz: "undan keyin" }, { de: "davor", uz: "undan oldin" },
    { de: "vorher", uz: "oldin" }, { de: "nachher", uz: "keyin (shu narsadan keyin)" },
    { de: "oben", uz: "yuqorida" }, { de: "unten", uz: "pastda" }, { de: "drinnen", uz: "ichkarida" },
    { de: "draußen", uz: "tashqarida" }, { de: "überall", uz: "hamma joyda" }, { de: "nirgendwo", uz: "hech qayerda" },
    { de: "fast", uz: "deyarli" }, { de: "ungefähr", uz: "taxminan" }, { de: "deshalb", uz: "shuning uchun" },
    { de: "trotzdem", uz: "shunga qaramay" }, { de: "wirklich", uz: "haqiqatan" }, { de: "übrigens", uz: "aytgancha" },
    { de: "sowieso", uz: "baribir" }, { de: "bald", uz: "tez orada" }, { de: "später", uz: "keyinroq" },
    { de: "sofort", uz: "darhol" }, { de: "gleich", uz: "hoziroq" }, { de: "wieder", uz: "yana" },
    { de: "damals", uz: "o'sha paytda" }, { de: "anfangs", uz: "dastlab" }, { de: "bisher", uz: "hozirgacha" },
    { de: "einmal", uz: "bir marta" }, { de: "zweimal", uz: "ikki marta" }, { de: "jedenfalls", uz: "har holda" },
    { de: "immerhin", uz: "baribir / hech bo'lmasa" }, { de: "beinahe", uz: "deyarli" },
    { de: "völlig", uz: "to'liq / butunlay" }, { de: "natürlich", uz: "albatta" }, { de: "bestimmt", uz: "aniq / albatta" },
    { de: "endlich", uz: "nihoyat" }, { de: "zumindest", uz: "kamida" }, { de: "mindestens", uz: "kamida (miqdor)" },
    { de: "höchstens", uz: "ko'pi bilan" }, { de: "keineswegs", uz: "hech qachon emas" },
    { de: "notfalls", uz: "zarur bo'lsa" }, { de: "ansonsten", uz: "aks holda" }, { de: "weiterhin", uz: "bundan keyin ham" },
  ],
};
