export const TIPS = [
  {
    number: "01", icon: "💬", title: "Xatolardan qo'rqma",
    short: "Xato qilish — o'rganishning bir qismi. Gapira boshlash eng muhimi!",
    detail: "Har bir so'zni mukammal talaffuz qilishga harakat qilma. Asosiysi — gapirish! 'Ich gehen morgen in der Markt' desang ham — tushuniladi. Vaqt o'tishi bilan o'z-o'zidan to'g'rilanadi."
  },
  {
    number: "02", icon: "📚", title: "Mustahkam asos yasat",
    short: "Asosiy so'zlar va grammatikani o'rgan — der/die/das, fe'llar, olmoshlar.",
    detail: "Barcha tartibsiz fe'llarni yod olishning hojati yo'q. Muhim narsalar: artiklar, olmoshlar, hozirgi zamon fe'llari, modal fe'llar va oddiy gap qurilishi."
  },
  {
    number: "03", icon: "🎧", title: "Tinglash va taqlid qil",
    short: "Podcast, video, qo'shiq tinglash — so'ng eshitganingni takrorla.",
    detail: "Gapni to'xtatib, baland ovozda takrorla. Ritm, urg'u va talaffuzni taqlid qil. Musiqa o'rganishga o'xshaydi — ko'p eshitsang, grammatikani bilmasdan ham aytib bera olasan."
  },
  {
    number: "04", icon: "🗣️", title: "Baland ovozda mashq qil",
    short: "Uyda yolg'iz bo'lsang ham — nemischa gapir! O'zingga gapir.",
    detail: "Ko'rayotganing, qilayotganing haqida nemischa gapir. O'zingni yozib ol va tinglang — qayerda qiynalayotganingni tezda payqaysan."
  },
  {
    number: "05", icon: "📱", title: "Nemischani kundalik hayotga kirit",
    short: "Telefon tilini nemischaga o'zgar, nemis video/musiqa ko'r.",
    detail: "Ertalab — nemischa YouTube. Yo'lda — podcast. Kechqurun — bolalar kitobini o'qi. Xarid ro'yxatini nemischa yoz. Nemischa 'fan' emas, hayotning bir qismi bo'lsin!"
  },
];

export const VOCAB = {
  Verben: [
    { de: "sein", uz: "bo'lmoq" }, { de: "haben", uz: "ega bo'lmoq" }, { de: "werden", uz: "bo'lmoq (kelajak)" },
    { de: "können", uz: "qila olmoq" }, { de: "müssen", uz: "kerak bo'lmoq" }, { de: "wollen", uz: "xohlamoq" },
    { de: "dürfen", uz: "ruxsat bo'lmoq" }, { de: "machen", uz: "qilmoq" }, { de: "sagen", uz: "aytmoq" },
    { de: "gehen", uz: "bormoq / yurmoq" }, { de: "kommen", uz: "kelmoq" }, { de: "geben", uz: "bermoq" },
    { de: "sehen", uz: "ko'rmoq" }, { de: "stehen", uz: "turmoq" }, { de: "finden", uz: "topmoq" },
    { de: "bleiben", uz: "qolmoq" }, { de: "liegen", uz: "yotmoq" }, { de: "nehmen", uz: "olmoq" },
    { de: "wissen", uz: "bilmoq" }, { de: "leben", uz: "yashmoq" }, { de: "bringen", uz: "olib kelmoq" },
    { de: "essen", uz: "yemoq" }, { de: "trinken", uz: "ichmoq" }, { de: "sprechen", uz: "gapirmoq" },
    { de: "schreiben", uz: "yozmoq" }, { de: "lesen", uz: "o'qimoq" }, { de: "fahren", uz: "haydamoq / bormoq" },
    { de: "kaufen", uz: "sotib olmoq" }, { de: "helfen", uz: "yordam bermoq" }, { de: "lernen", uz: "o'rganmoq" },
    { de: "fragen", uz: "so'ramoq" }, { de: "antworten", uz: "javob bermoq" }, { de: "spielen", uz: "o'ynamoq" },
    { de: "arbeiten", uz: "ishlashmoq" }, { de: "denken", uz: "o'ylamoq" }, { de: "glauben", uz: "ishonmoq" },
    { de: "brauchen", uz: "kerak bo'lmoq" }, { de: "suchen", uz: "qidirmoq" }, { de: "zeigen", uz: "ko'rsatmoq" },
    { de: "versuchen", uz: "urinmoq" }, { de: "tragen", uz: "ko'tarmoq / kiymoq" }, { de: "halten", uz: "ushlamoq" },
    { de: "öffnen", uz: "ochmoq" }, { de: "schließen", uz: "yopmoq" }, { de: "beginnen", uz: "boshlamoq" },
    { de: "enden", uz: "tugamoq" }, { de: "laufen", uz: "yugurmoq" }, { de: "sitzen", uz: "o'tirmoq" },
    { de: "schlafen", uz: "uxlamoq" }, { de: "wohnen", uz: "yashmoq (turmoq)" }, { de: "heißen", uz: "atalmoq / ismim" },
    { de: "bekommen", uz: "olmoq / qabul qilmoq" }, { de: "verlieren", uz: "yo'qotmoq" }, { de: "gewinnen", uz: "yutmoq" },
    { de: "fühlen", uz: "his qilmoq" }, { de: "treffen", uz: "uchrashmoq" }, { de: "kennen", uz: "tanish bo'lmoq" },
    { de: "hören", uz: "eshitmoq" }, { de: "erklären", uz: "tushuntirmoq" }, { de: "feiern", uz: "nishonlamoq" },
    { de: "vergessen", uz: "unutmoq" }, { de: "erinnern", uz: "eslamoq" }, { de: "bedeuten", uz: "anglatmoq" },
    { de: "zahlen", uz: "to'lamoq" }, { de: "schicken", uz: "yubormoq" }, { de: "bestellen", uz: "buyurtma bermoq" },
    { de: "kochen", uz: "pishirmoq" }, { de: "backen", uz: "non/tort pishirmoq" }, { de: "tanzen", uz: "raqsga tushmoq" },
    { de: "malen", uz: "rasm chizmoq" }, { de: "reparieren", uz: "ta'mirlashmoq" }, { de: "wechseln", uz: "almashtirmoq" },
  ],
  Nomen: [
    { de: "der Mensch", uz: "inson" }, { de: "die Frau", uz: "ayol" }, { de: "der Mann", uz: "erkak" },
    { de: "das Kind", uz: "bola" }, { de: "das Haus", uz: "uy" }, { de: "die Wohnung", uz: "kvartira" },
    { de: "das Zimmer", uz: "xona" }, { de: "die Tür", uz: "eshik" }, { de: "das Fenster", uz: "deraza" },
    { de: "der Tisch", uz: "stol" }, { de: "der Stuhl", uz: "stul" }, { de: "das Bett", uz: "karavot" },
    { de: "das Sofa", uz: "divan" }, { de: "der Schrank", uz: "shkaf" }, { de: "die Küche", uz: "oshxona" },
    { de: "das Bad", uz: "hammom" }, { de: "der Garten", uz: "bog'" }, { de: "die Straße", uz: "ko'cha" },
    { de: "der Weg", uz: "yo'l" }, { de: "die Stadt", uz: "shahar" }, { de: "das Dorf", uz: "qishloq" },
    { de: "das Auto", uz: "mashina" }, { de: "der Bus", uz: "avtobus" }, { de: "der Zug", uz: "poyezd" },
    { de: "das Fahrrad", uz: "velosiped" }, { de: "das Essen", uz: "ovqat" }, { de: "das Brot", uz: "non" },
    { de: "das Wasser", uz: "suv" }, { de: "der Kaffee", uz: "qahva" }, { de: "der Tee", uz: "choy" },
    { de: "das Fleisch", uz: "go'sht" }, { de: "das Gemüse", uz: "sabzavot" }, { de: "das Obst", uz: "meva" },
    { de: "der Apfel", uz: "olma" }, { de: "die Banane", uz: "banan" }, { de: "die Kartoffel", uz: "kartoshka" },
    { de: "der Reis", uz: "guruch" }, { de: "die Nudeln", uz: "makaron" }, { de: "die Milch", uz: "sut" },
    { de: "der Käse", uz: "pishloq" }, { de: "das Ei", uz: "tuxum" }, { de: "die Arbeit", uz: "ish" },
    { de: "die Schule", uz: "maktab" }, { de: "die Universität", uz: "universitet" }, { de: "der Lehrer", uz: "o'qituvchi" },
    { de: "der Schüler", uz: "o'quvchi" }, { de: "die Sprache", uz: "til" }, { de: "das Wort", uz: "so'z" },
    { de: "der Satz", uz: "gap / jumla" }, { de: "das Buch", uz: "kitob" }, { de: "die Zeitung", uz: "gazeta" },
    { de: "der Brief", uz: "xat" }, { de: "der Computer", uz: "kompyuter" }, { de: "das Telefon", uz: "telefon" },
    { de: "die Zeit", uz: "vaqt" }, { de: "der Tag", uz: "kun" }, { de: "die Nacht", uz: "tun" },
    { de: "der Morgen", uz: "ertalab" }, { de: "der Abend", uz: "kechqurun" }, { de: "der Nachmittag", uz: "tushdan keyin" },
    { de: "das Geld", uz: "pul" }, { de: "der Preis", uz: "narx" }, { de: "die Hilfe", uz: "yordam" },
    { de: "das Problem", uz: "muammo" }, { de: "der Fehler", uz: "xato" }, { de: "der Name", uz: "ism" },
    { de: "der Geburtstag", uz: "tug'ilgan kun" }, { de: "der Freund", uz: "do'st (erkak)" }, { de: "die Freundin", uz: "do'st (ayol)" },
    { de: "die Familie", uz: "oila" }, { de: "der Vater", uz: "ota" }, { de: "die Mutter", uz: "ona" },
    { de: "der Bruder", uz: "aka / uka" }, { de: "die Schwester", uz: "opa / singil" }, { de: "der Sohn", uz: "o'g'il" },
    { de: "die Tochter", uz: "qiz (farzand)" }, { de: "der Hund", uz: "it" }, { de: "die Katze", uz: "mushuk" },
    { de: "das Wetter", uz: "ob-havo" }, { de: "die Sonne", uz: "quyosh" }, { de: "der Regen", uz: "yomg'ir" },
    { de: "der Schnee", uz: "qor" }, { de: "der Wind", uz: "shamol" }, { de: "der Baum", uz: "daraxt" },
    { de: "die Blume", uz: "gul" }, { de: "der Berg", uz: "tog'" }, { de: "der See", uz: "ko'l" },
    { de: "der Fluss", uz: "daryo" }, { de: "das Land", uz: "mamlakat" }, { de: "die Musik", uz: "musiqa" },
    { de: "das Lied", uz: "qo'shiq" }, { de: "der Film", uz: "film" }, { de: "das Jahr", uz: "yil" },
    { de: "der Monat", uz: "oy" }, { de: "die Woche", uz: "hafta" }, { de: "die Minute", uz: "daqiqa" },
  ],
  Adjektive: [
    { de: "gut", uz: "yaxshi" }, { de: "schlecht", uz: "yomon" }, { de: "groß", uz: "katta" },
    { de: "klein", uz: "kichik" }, { de: "lang", uz: "uzun" }, { de: "kurz", uz: "qisqa" },
    { de: "schön", uz: "chiroyli" }, { de: "hässlich", uz: "xunuk" }, { de: "neu", uz: "yangi" },
    { de: "alt", uz: "eski / keksa" }, { de: "kalt", uz: "sovuq" }, { de: "warm", uz: "iliq" },
    { de: "heiß", uz: "issiq" }, { de: "teuer", uz: "qimmat" }, { de: "billig", uz: "arzon" },
    { de: "schnell", uz: "tez" }, { de: "langsam", uz: "sekin" }, { de: "leicht", uz: "oson / yengil" },
    { de: "schwer", uz: "og'ir / qiyin" }, { de: "laut", uz: "baland (ovoz)" }, { de: "leise", uz: "past (ovoz)" },
    { de: "hell", uz: "yorqin" }, { de: "dunkel", uz: "qorong'i" }, { de: "richtig", uz: "to'g'ri" },
    { de: "falsch", uz: "noto'g'ri" }, { de: "voll", uz: "to'la" }, { de: "leer", uz: "bo'sh" },
    { de: "nah", uz: "yaqin" }, { de: "fern", uz: "uzoq" }, { de: "jung", uz: "yosh" },
    { de: "modern", uz: "zamonaviy" }, { de: "dick", uz: "yo'g'on / semiz" }, { de: "dünn", uz: "ingichka / ozg'in" },
    { de: "breit", uz: "keng" }, { de: "eng", uz: "tor" }, { de: "tief", uz: "chuqur" },
    { de: "hoch", uz: "baland" }, { de: "sauber", uz: "toza" }, { de: "schmutzig", uz: "iflos" },
    { de: "süß", uz: "shirin" }, { de: "sauer", uz: "nordon" }, { de: "bitter", uz: "achchiq" },
    { de: "frisch", uz: "yangi / fresh" }, { de: "nass", uz: "ho'l" }, { de: "trocken", uz: "quruq" },
    { de: "rund", uz: "yumaloq" }, { de: "eckig", uz: "burchakli" }, { de: "lecker", uz: "mazali" },
    { de: "bekannt", uz: "mashhur / tanish" }, { de: "bequem", uz: "qulay" }, { de: "freundlich", uz: "do'stona" },
    { de: "froh", uz: "xursand" }, { de: "traurig", uz: "g'amgin" }, { de: "wichtig", uz: "muhim" },
    { de: "einfach", uz: "oddiy / oson" }, { de: "schwierig", uz: "qiyin" }, { de: "müde", uz: "charchagan" },
    { de: "wach", uz: "uyg'oq" }, { de: "nett", uz: "yoqimli" }, { de: "böse", uz: "yomon / g'azablangan" },
    { de: "interessant", uz: "qiziqarli" }, { de: "langweilig", uz: "zerikarli" }, { de: "spannend", uz: "hayajonli" },
    { de: "möglich", uz: "mumkin" }, { de: "unmöglich", uz: "mumkin emas" }, { de: "gesund", uz: "sog'lom" },
    { de: "krank", uz: "kasal" }, { de: "reich", uz: "boy" }, { de: "arm", uz: "kambag'al" },
    { de: "klar", uz: "aniq" }, { de: "lustig", uz: "kulgili" }, { de: "ernst", uz: "jiddiy" },
    { de: "vorsichtig", uz: "ehtiyotkor" }, { de: "gefährlich", uz: "xavfli" }, { de: "sicher", uz: "xavfsiz" },
    { de: "stark", uz: "kuchli" }, { de: "schwach", uz: "kuchsiz" }, { de: "kühl", uz: "salqin" },
    { de: "glatt", uz: "silliq" }, { de: "direkt", uz: "to'g'ridan-to'g'ri" }, { de: "pünktlich", uz: "o'z vaqtida" },
    { de: "spät", uz: "kech" }, { de: "früh", uz: "erta" }, { de: "schmal", uz: "tor" },
    { de: "clever", uz: "aqlli" }, { de: "dumm", uz: "ahmoq" }, { de: "fest", uz: "qattiq" },
    { de: "weich", uz: "yumshoq" }, { de: "scharf", uz: "o'tkir" }, { de: "normal", uz: "oddiy / normal" },
  ],
  Adverbien: [
    { de: "jetzt", uz: "hozir" }, { de: "hier", uz: "bu yerda" }, { de: "dort", uz: "u yerda" },
    { de: "heute", uz: "bugun" }, { de: "morgen", uz: "ertaga" }, { de: "gestern", uz: "kecha" },
    { de: "immer", uz: "doimo" }, { de: "nie", uz: "hech qachon" }, { de: "oft", uz: "ko'pincha" },
    { de: "selten", uz: "kamdan-kam" }, { de: "manchmal", uz: "ba'zan" }, { de: "vielleicht", uz: "ehtimol" },
    { de: "leider", uz: "afsuski" }, { de: "gern", uz: "mamnuniyat bilan" }, { de: "sehr", uz: "juda" },
    { de: "auch", uz: "ham" }, { de: "schon", uz: "allaqachon" }, { de: "noch", uz: "hali" },
    { de: "dann", uz: "keyin" }, { de: "danach", uz: "undan keyin" }, { de: "davor", uz: "undan oldin" },
    { de: "vorher", uz: "oldin" }, { de: "nachher", uz: "keyin (shu narsadan keyin)" },
    { de: "oben", uz: "yuqorida" }, { de: "unten", uz: "pastda" }, { de: "drinnen", uz: "ichkarida" },
    { de: "draußen", uz: "tashqarida" }, { de: "überall", uz: "hamma joyda" }, { de: "nirgendwo", uz: "hech qayerda" },
    { de: "fast", uz: "deyarli" }, { de: "ungefähr", uz: "taxminan" }, { de: "deshalb", uz: "shuning uchun" },
    { de: "trotzdem", uz: "shunga qaramay" }, { de: "wirklich", uz: "haqiqatan" }, { de: "übrigens", uz: "aytgancha" },
    { de: "sowieso", uz: "baribir" }, { de: "bald", uz: "tez orada" }, { de: "später", uz: "keyinroq" },
    { de: "sofort", uz: "darhol" }, { de: "gleich", uz: "hoziroq" }, { de: "wieder", uz: "yana" },
    { de: "damals", uz: "o'sha paytda" }, { de: "anfangs", uz: "dastlab" }, { de: "bisher", uz: "hozirgacha" },
    { de: "einmal", uz: "bir marta" }, { de: "zweimal", uz: "ikki marta" }, { de: "jedenfalls", uz: "har holda" },
    { de: "immerhin", uz: "baribir / hech bo'lmasa" }, { de: "beinahe", uz: "deyarli" },
    { de: "völlig", uz: "to'liq / butunlay" }, { de: "natürlich", uz: "albatta" }, { de: "bestimmt", uz: "aniq / albatta" },
    { de: "endlich", uz: "nihoyat" }, { de: "zumindest", uz: "kamida" }, { de: "mindestens", uz: "kamida (miqdor)" },
    { de: "höchstens", uz: "ko'pi bilan" }, { de: "keineswegs", uz: "hech qachon emas" },
    { de: "notfalls", uz: "zarur bo'lsa" }, { de: "ansonsten", uz: "aks holda" }, { de: "weiterhin", uz: "bundan keyin ham" },
  ],
  Zahlen: [
    { de: "ein", uz: "bir" }, { de: "zwei", uz: "ikki" }, { de: "drei", uz: "uch" },
    { de: "vier", uz: "to'rt" }, { de: "fünf", uz: "besh" }, { de: "sechs", uz: "olti" },
    { de: "sieben", uz: "yetti" }, { de: "acht", uz: "sakkiz" }, { de: "neun", uz: "to'qqiz" },
    { de: "zehn", uz: "o'n" }, { de: "elf", uz: "o'n bir" }, { de: "zwölf", uz: "o'n ikki" },
    { de: "zwanzig", uz: "yigirma" }, { de: "dreißig", uz: "o'ttiz" }, { de: "vierzig", uz: "qirq" },
    { de: "fünfzig", uz: "ellik" }, { de: "hundert", uz: "yuz" }, { de: "tausend", uz: "ming" },
    { de: "erste", uz: "birinchi" }, { de: "zweite", uz: "ikkinchi" }, { de: "dritte", uz: "uchinchi" },
    { de: "null", uz: "nol" }, { de: "einmal", uz: "bir marta" }, { de: "zweimal", uz: "ikki marta" },
    { de: "halb", uz: "yarmi" }, { de: "viertel", uz: "chorak" }, { de: "die Uhr", uz: "soat" },
    { de: "die Stunde", uz: "soat (vaqt)" }, { de: "die Minute", uz: "daqiqa" }, { de: "die Sekunde", uz: "soniya" },
  ],
  Farben: [
    { de: "rot", uz: "qizil" }, { de: "blau", uz: "ko'k" }, { de: "grün", uz: "yashil" },
    { de: "gelb", uz: "sariq" }, { de: "schwarz", uz: "qora" }, { de: "weiß", uz: "oq" },
    { de: "grau", uz: "kulrang" }, { de: "braun", uz: "jigarrang" }, { de: "orange", uz: "to'q sariq / apelsin rang" },
    { de: "lila", uz: "binafsha" }, { de: "pink", uz: "pushti" }, { de: "türkis", uz: "moviy-yashil" },
    { de: "gold", uz: "oltin rang" }, { de: "silber", uz: "kumush rang" }, { de: "hell", uz: "och (rang)" },
    { de: "dunkel", uz: "to'q (rang)" }, { de: "bunt", uz: "rang-barang" }, { de: "farbig", uz: "rangli" },
    { de: "transparent", uz: "shaffof" }, { de: "beige", uz: "och jigarrang" },
  ],
  Familie: [
    { de: "die Mutter", uz: "ona" }, { de: "der Vater", uz: "ota" }, { de: "die Schwester", uz: "opa / singil" },
    { de: "der Bruder", uz: "aka / uka" }, { de: "die Großmutter", uz: "buvi / momо" }, { de: "der Großvater", uz: "bobo" },
    { de: "die Tochter", uz: "qiz (farzand)" }, { de: "der Sohn", uz: "o'g'il" }, { de: "die Tante", uz: "xola / amaki xotini" },
    { de: "der Onkel", uz: "tog'a / amaki" }, { de: "die Cousine", uz: "amakivacha (qiz)" }, { de: "der Cousin", uz: "amakivacha (o'g'il)" },
    { de: "die Eltern", uz: "ota-ona" }, { de: "die Familie", uz: "oila" }, { de: "das Baby", uz: "chaqaloq" },
    { de: "das Kind", uz: "bola" }, { de: "die Frau", uz: "xotin" }, { de: "der Mann", uz: "er" },
    { de: "verheiratet", uz: "turmush qurgan" }, { de: "ledig", uz: "bo'ydoq / turmush qurmagan" }, { de: "geschieden", uz: "ajrashgan" },
    { de: "die Hochzeit", uz: "to'y / nikoh" }, { de: "der Ehemann", uz: "er (rasmiy)" }, { de: "die Ehefrau", uz: "xotin (rasmiy)" },
    { de: "die Geschwister", uz: "aka-uka / opa-singillar" },
  ],
  Essen: [
    { de: "das Brot", uz: "non" }, { de: "die Butter", uz: "sariyog'" }, { de: "das Fleisch", uz: "go'sht" },
    { de: "der Fisch", uz: "baliq" }, { de: "das Gemüse", uz: "sabzavot" }, { de: "das Obst", uz: "meva" },
    { de: "die Kartoffel", uz: "kartoshka" }, { de: "der Reis", uz: "guruch" }, { de: "die Nudeln", uz: "makaron" },
    { de: "die Suppe", uz: "sho'rva" }, { de: "der Salat", uz: "salat" }, { de: "der Käse", uz: "pishloq" },
    { de: "das Ei", uz: "tuxum" }, { de: "die Milch", uz: "sut" }, { de: "der Kaffee", uz: "qahva" },
    { de: "der Tee", uz: "choy" }, { de: "das Wasser", uz: "suv" }, { de: "der Saft", uz: "sharbat" },
    { de: "das Bier", uz: "pivo" }, { de: "der Wein", uz: "vino" }, { de: "die Pizza", uz: "pitsa" },
    { de: "der Kuchen", uz: "tort / pirog" }, { de: "das Eis", uz: "muzqaymoq" }, { de: "die Schokolade", uz: "shokolad" },
    { de: "der Zucker", uz: "shakar" }, { de: "das Salz", uz: "tuz" }, { de: "der Pfeffer", uz: "qalampir" },
    { de: "das Öl", uz: "yog'" }, { de: "frisch", uz: "yangi / fresh" }, { de: "lecker", uz: "mazali" },
  ],
  Reisen: [
    { de: "das Flugzeug", uz: "samolyot" }, { de: "der Zug", uz: "poyezd" }, { de: "das Auto", uz: "mashina" },
    { de: "der Bus", uz: "avtobus" }, { de: "das Schiff", uz: "kema" }, { de: "das Hotel", uz: "mehmonxona" },
    { de: "das Zimmer", uz: "xona" }, { de: "der Bahnhof", uz: "temir yo'l stantsiyasi" }, { de: "der Flughafen", uz: "aeroport" },
    { de: "die Reise", uz: "sayohat" }, { de: "der Koffer", uz: "chamadon" }, { de: "der Pass", uz: "pasport" },
    { de: "das Ticket", uz: "chipta" }, { de: "die Karte", uz: "xarita / karta" }, { de: "die Straße", uz: "ko'cha / yo'l" },
    { de: "die Stadt", uz: "shahar" }, { de: "das Land", uz: "mamlakat" }, { de: "die Grenze", uz: "chegara" },
    { de: "der Tourist", uz: "turist" }, { de: "die Sehenswürdigkeit", uz: "diqqatga sazovor joy" }, { de: "buchen", uz: "bron qilmoq" },
    { de: "ankommen", uz: "kelmoq / yetib kelmoq" }, { de: "abfahren", uz: "jo'namoq / ketmoq" }, { de: "einsteigen", uz: "minmoq (transport)" },
    { de: "aussteigen", uz: "tushmoq (transportdan)" },
  ],
  Körper: [
    { de: "der Kopf", uz: "bosh" }, { de: "das Gesicht", uz: "yuz" }, { de: "das Auge", uz: "ko'z" },
    { de: "das Ohr", uz: "quloq" }, { de: "die Nase", uz: "burun" }, { de: "der Mund", uz: "og'iz" },
    { de: "der Zahn", uz: "tish" }, { de: "der Hals", uz: "bo'yin" }, { de: "die Schulter", uz: "yelka" },
    { de: "der Arm", uz: "qo'l (tirsak va yuqori qism)" }, { de: "die Hand", uz: "qo'l (kaft)" }, { de: "der Finger", uz: "barmoq" },
    { de: "der Bauch", uz: "qorin" }, { de: "das Bein", uz: "oyoq" }, { de: "das Knie", uz: "tizza" },
    { de: "der Fuß", uz: "oyoq (panja)" }, { de: "der Rücken", uz: "orqa" }, { de: "das Herz", uz: "yurak" },
    { de: "die Lunge", uz: "o'pka" }, { de: "die Haut", uz: "teri" }, { de: "krank", uz: "kasal" },
    { de: "gesund", uz: "sog'lom" }, { de: "der Schmerz", uz: "og'riq" }, { de: "die Medizin", uz: "dori / meditsina" },
    { de: "der Arzt", uz: "shifokor" },
  ],
  Berufe: [
    { de: "der Arzt", uz: "shifokor (erkak)" }, { de: "die Ärztin", uz: "shifokor (ayol)" }, { de: "der Lehrer", uz: "o'qituvchi (erkak)" },
    { de: "die Lehrerin", uz: "o'qituvchi (ayol)" }, { de: "der Ingenieur", uz: "muhandis" }, { de: "der Koch", uz: "oshpaz" },
    { de: "der Fahrer", uz: "haydovchi" }, { de: "der Verkäufer", uz: "sotuvchi" }, { de: "der Manager", uz: "menejer" },
    { de: "der Direktor", uz: "direktor" }, { de: "der Polizist", uz: "politsiyachi" }, { de: "der Feuerwehrmann", uz: "o't o'chiruvchi" },
    { de: "der Pilot", uz: "pilot" }, { de: "der Architekt", uz: "arxitektor" }, { de: "der Rechtsanwalt", uz: "advokat" },
    { de: "der Journalist", uz: "jurnalist" }, { de: "der Programmierer", uz: "dasturchi" }, { de: "der Designer", uz: "dizayner" },
    { de: "der Musiker", uz: "musiqachi" }, { de: "der Schauspieler", uz: "aktyоr" }, { de: "arbeiten", uz: "ishlashmoq" },
    { de: "der Beruf", uz: "kasb / mutaxassislik" }, { de: "die Arbeit", uz: "ish / mehnat" }, { de: "das Büro", uz: "ofis / idora" },
    { de: "der Chef", uz: "xo'jayin / boss" },
  ],
  Natur: [
    { de: "der Baum", uz: "daraxt" }, { de: "die Blume", uz: "gul" }, { de: "das Gras", uz: "o't / maysazor" },
    { de: "der Berg", uz: "tog'" }, { de: "der Fluss", uz: "daryo" }, { de: "der See", uz: "ko'l" },
    { de: "das Meer", uz: "dengiz" }, { de: "der Wald", uz: "o'rmon" }, { de: "der Park", uz: "park" },
    { de: "die Luft", uz: "havo" }, { de: "das Wasser", uz: "suv" }, { de: "die Erde", uz: "yer / tuproq" },
    { de: "der Himmel", uz: "osmon" }, { de: "die Sonne", uz: "quyosh" }, { de: "der Mond", uz: "oy" },
    { de: "der Stern", uz: "yulduz" }, { de: "der Regen", uz: "yomg'ir" }, { de: "der Schnee", uz: "qor" },
    { de: "der Wind", uz: "shamol" }, { de: "die Wolke", uz: "bulut" }, { de: "heiß", uz: "issiq" },
    { de: "kalt", uz: "sovuq" }, { de: "warm", uz: "iliq" }, { de: "kühl", uz: "salqin" },
    { de: "schön", uz: "chiroyli / go'zal" },
  ],
};

export const CAT_META = {
  Verben: { icon: "⚡", color: "#e5c158", label: "Fe'llar" },
  Nomen: { icon: "📦", color: "#1cb0f6", label: "Otlar" },
  Adjektive: { icon: "🎨", color: "#a435f0", label: "Sifatlar" },
  Adverbien: { icon: "💬", color: "#ff9600", label: "Ravishlar" },
  Zahlen: { icon: "🔢", color: "#ff4b4b", label: "Sonlar" },
  Farben: { icon: "🌈", color: "#58cc02", label: "Ranglar" },
  Familie: { icon: "👨‍👩‍👧", color: "#ff6b9d", label: "Oila" },
  Essen: { icon: "🍕", color: "#ff9600", label: "Taom" },
  Reisen: { icon: "✈️", color: "#1cb0f6", label: "Sayohat" },
  Körper: { icon: "💪", color: "#e63946", label: "Tana" },
  Berufe: { icon: "👔", color: "#6c5ce7", label: "Kasblar" },
  Natur: { icon: "🌿", color: "#58cc02", label: "Tabiat" },
};

export const LEVELS = [
  // Unit 1: Fe'llar
  {
    id: 1,
    unit: 1,
    unitTitle: "1-Bosqich: Harakat Fe'llari",
    title: "Asosiy Fe'llar",
    desc: "Kundalik eng muhim nemischa harakat fe'llarini o'rganing.",
    category: "Verben",
    words: ["sein", "haben", "machen", "sagen", "gehen", "kommen", "sehen", "geben", "stehen", "finden"],
    sentence: { de: "Ich gehe nach Hause", uz: "Men uyga ketyapman" }
  },
  {
    id: 2,
    unit: 1,
    unitTitle: "1-Bosqich: Harakat Fe'llari",
    title: "Kundalik Hayot",
    desc: "Yemoq, ichmoq, o'qish va yozishga oid fe'llar.",
    category: "Verben",
    words: ["leben", "essen", "trinken", "schreiben", "lesen", "arbeiten", "schlafen", "wohnen", "heißen", "kaufen"],
    sentence: { de: "Wir essen heute Brot", uz: "Biz bugun non yeyapmiz" }
  },
  {
    id: 3,
    unit: 1,
    unitTitle: "1-Bosqich: Harakat Fe'llari",
    title: "Muloqot va O'yin",
    desc: "Yordam so'rash, o'ylash va so'zlashish fe'llari.",
    category: "Verben",
    words: ["wissen", "denken", "sprechen", "fragen", "antworten", "spielen", "brauchen", "suchen", "zeigen", "helfen"],
    sentence: { de: "Kannst du mir helfen", uz: "Menga yordam bera olasanmi" }
  },
  {
    id: 4,
    unit: 1,
    unitTitle: "1-Bosqich: Harakat Fe'llari",
    title: "Modal va Murakkab Fe'llar",
    desc: "Qila olmoq, ruxsat olmoq va ketmoq kabi fe'llar.",
    category: "Verben",
    words: ["können", "müssen", "wollen", "dürfen", "werden", "bleiben", "liegen", "nehmen", "bringen", "fahren"],
    sentence: { de: "Ich muss Deutsch lernen", uz: "Men nemis tilini o'rganishim kerak" }
  },
  // Unit 2: Otlar
  {
    id: 5,
    unit: 2,
    unitTitle: "2-Bosqich: Otlar va Mavjudlik",
    title: "Inson va Oila",
    desc: "Oila a'zolari va shaxslarga doir otlar.",
    category: "Nomen",
    words: ["der Mensch", "die Frau", "der Mann", "das Kind", "der Vater", "die Mutter", "der Bruder", "die Schwester", "der Sohn", "die Tochter"],
    sentence: { de: "Meine Familie ist groß", uz: "Mening oilam katta" }
  },
  {
    id: 6,
    unit: 2,
    unitTitle: "2-Bosqich: Otlar va Mavjudlik",
    title: "Uy va Jihozlar",
    desc: "Turar joy va xona ichidagi asosiy jihozlar.",
    category: "Nomen",
    words: ["das Haus", "die Wohnung", "das Zimmer", "die Tür", "das Fenster", "der Tisch", "der Stuhl", "das Bett", "das Sofa", "der Schrank"],
    sentence: { de: "Das Haus ist schön", uz: "Uy chiroyli" }
  },
  {
    id: 7,
    unit: 2,
    unitTitle: "2-Bosqich: Otlar va Mavjudlik",
    title: "Yegulik va Ichimliklar",
    desc: "Meva-sabzavotlar va turli taom nomlari.",
    category: "Nomen",
    words: ["das Essen", "das Brot", "das Wasser", "der Kaffee", "der Tee", "das Fleisch", "das Gemüse", "das Obst", "der Apfel", "die Banane"],
    sentence: { de: "Ich trinke kalten Tee", uz: "Men sovuq choy ichaman" }
  },
  {
    id: 8,
    unit: 2,
    unitTitle: "2-Bosqich: Otlar va Mavjudlik",
    title: "Maktab va Jamiyat",
    desc: "Ta'lim, transport va vaqtga oid muhim otlar.",
    category: "Nomen",
    words: ["die Schule", "die Universität", "der Lehrer", "der Schüler", "die Sprache", "das Wort", "der Satz", "das Buch", "das Auto", "der Zug"],
    sentence: { de: "Das Buch ist interessant", uz: "Kitob qiziqarli" }
  },
  // Unit 3: Sifatlar
  {
    id: 9,
    unit: 3,
    unitTitle: "3-Bosqich: Sifatlar va Ta'riflar",
    title: "Hajm va Asosiy Sifatlar",
    desc: "Narsalarni tavsiflash uchun eng kerakli sifatlar.",
    category: "Adjektive",
    words: ["gut", "schlecht", "groß", "klein", "lang", "kurz", "schön", "hässlich", "neu", "alt"],
    sentence: { de: "Der Mann ist alt", uz: "Erkak kishi qari" }
  },
  {
    id: 10,
    unit: 3,
    unitTitle: "3-Bosqich: Sifatlar va Ta'riflar",
    title: "Holat va Harorat",
    desc: "Issiq-sovuq, tezkorlik va narx-navoga doir sifatlar.",
    category: "Adjektive",
    words: ["kalt", "warm", "heiß", "teuer", "billig", "schnell", "langsam", "leicht", "schwer", "modern"],
    sentence: { de: "Das Auto fährt schnell", uz: "Mashina tez yuradi" }
  },
  {
    id: 11,
    unit: 3,
    unitTitle: "3-Bosqich: Sifatlar va Ta'riflar",
    title: "Hissiyot va Qulaylik",
    desc: "Tozalik, mazalilik va inson kayfiyatlari.",
    category: "Adjektive",
    words: ["sauber", "schmutzig", "süß", "sauer", "lecker", "froh", "traurig", "müde", "wach", "nett"],
    sentence: { de: "Ich bin sehr müde", uz: "Men juda charchaganman" }
  },
  {
    id: 12,
    unit: 3,
    unitTitle: "3-Bosqich: Sifatlar va Ta'riflar",
    title: "Mantiqiy Belgilar",
    desc: "Muhimlik, oson-qiyinlik va xavfsizlik belgilari.",
    category: "Adjektive",
    words: ["wichtig", "einfach", "schwierig", "interessant", "langweilig", "möglich", "unmöglich", "gesund", "krank", "sicher"],
    sentence: { de: "Deutsch ist nicht schwierig", uz: "Nemis tili qiyin emas" }
  },
  // Unit 4: Ravishlar
  {
    id: 13,
    unit: 4,
    unitTitle: "4-Bosqich: Ravishlar va Vaqt",
    title: "Vaqt Ravishlari",
    desc: "Harakatlar qachon sodir bo'lishini ko'rsatuvchi ravishlar.",
    category: "Adverbien",
    words: ["jetzt", "heute", "morgen", "gestern", "immer", "nie", "manchmal", "oft", "selten", "bald"],
    sentence: { de: "Ich lerne heute Deutsch", uz: "Men bugun nemis tili o'rganyapman" }
  },
  {
    id: 14,
    unit: 4,
    unitTitle: "4-Bosqich: Ravishlar va Vaqt",
    title: "Makon va Joy",
    desc: "Qayerda ekanligini ifodalovchi joy ravishlari.",
    category: "Adverbien",
    words: ["hier", "dort", "oben", "unten", "drinnen", "draußen", "überall", "nirgendwo", "fast", "sowieso"],
    sentence: { de: "Es ist warm draußen", uz: "Tashqarida iliq" }
  },
  {
    id: 15,
    unit: 4,
    unitTitle: "4-Bosqich: Ravishlar va Vaqt",
    title: "Miqdor va Taxmin",
    desc: "Daraja, ehtimollik va ketma-ketlik ravishlari.",
    category: "Adverbien",
    words: ["vielleicht", "leider", "gern", "sehr", "auch", "schon", "noch", "dann", "danach", "davor"],
    sentence: { de: "Ich trinke sehr gern Kaffee", uz: "Men qahvani juda mamnuniyat bilan ichaman" }
  },
  {
    id: 16,
    unit: 4,
    unitTitle: "4-Bosqich: Ravishlar va Vaqt",
    title: "Tezkorlik va Natija",
    desc: "Darhol, yana va nihoyat kabi kuchaytiruvchi ravishlar.",
    category: "Adverbien",
    words: ["sofort", "gleich", "wieder", "damals", "natürlich", "bestimmt", "endlich", "zumindest", "mindestens", "ansonsten"],
    sentence: { de: "Wir gewinnen sofort das Spiel", uz: "Biz darhol o'yinni yutamiz" }
  }
];

export const DAILY_WORDS = [
  { de: "lernen", uz: "o'rganmoq", exampleDe: "Ich lerne jeden Tag Deutsch mit Blitzi.", exampleUz: "Men har kuni Blitzi yordamida nemis tilini o'rganaman." },
  { de: "sprechen", uz: "gapirmoq", exampleDe: "Er spricht fließend und selbstbewusst Deutsch.", exampleUz: "U nemis tilida ravon va ishonch bilan gapiradi." },
  { de: "der Erfolg", uz: "muvaffaqiyat", exampleDe: "Fleiß ist der Schlüssel zum Erfolg beim Sprachenlernen.", exampleUz: "G'ayrat (mehnatsevarlik) — til o'rganishda muvaffaqiyat kalitidir." },
  { de: "verstehen", uz: "tushunmoq", exampleDe: "Mit etwas Übung kann ich deutsche Podcasts gut verstehen.", exampleUz: "Biroz mashq bilan nemischa podkastlarni yaxshi tushuna olaman." },
  { de: "versuchen", uz: "urinib ko'rmoq / harakat qilmoq", exampleDe: "Versuche immer, auf Deutsch zu denken.", exampleUz: "Doimo nemis tilida o'ylashga harakat qiling." },
  { de: "die Geduld", uz: "sabr-toqat", exampleDe: "Sprachenlernen braucht Zeit und viel Geduld.", exampleUz: "Til o'rganish vaqt va ko'p sabr-toqat talab qiladi." },
  { de: "verbessern", uz: "yaxshilamoq / rivojlantirmoq", exampleDe: "Ich möchte meinen deutschen Wortschatz verbessern.", exampleUz: "Men nemischa so'z boyligimni yaxshilamoqchiman." },
  { de: "die Gewohnheit", uz: "odat", exampleDe: "Tägliches Lernen ist eine großartige Gewohnheit.", exampleUz: "Har kuni o'rganish — ajoyib odatdir." },
  { de: "glauben", uz: "ishonmoq", exampleDe: "Glaube an dich selbst und deine Fähigkeiten!", exampleUz: "O'zingizga va qobiliyatingizga ishoning!" },
  { de: "erreichen", uz: "erishmoq", exampleDe: "Ich werde mein Ziel erreichen, fließend Deutsch zu sprechen.", exampleUz: "Nemis tilida ravon gapirish maqsadimga erishaman." },
  { de: "arbeiten", uz: "ishlamoq", exampleDe: "Ich arbeite als Entwickler in Deutschland.", exampleUz: "Men Germaniyada dasturchi bo'lib ishlayman." },
  { de: "reisen", uz: "sayohat qilmoq", exampleDe: "Ich reise sehr gerne in neue Städte.", exampleUz: "Men yangi shaharlarga sayohat qilishni juda yaxshi ko'raman." },
  { de: "die Gesundheit", uz: "sog'lik", exampleDe: "Gesundheit ist der größte Reichtum.", exampleUz: "Sog'lik — eng katta boylikdir." },
  { de: "der Traum", uz: "orzu / tush", exampleDe: "Folge deinen Träumen und gib niemals auf.", exampleUz: "Orzularingizga ergashing va hech qachon taslim bo'lmang." },
  { de: "wichtig", uz: "muhim", exampleDe: "Es ist wichtig, regelmäßig Vokabeln zu wiederholen.", exampleUz: "Doimiy ravishda so'zlarni takrorlab turish muhimdir." },
  { de: "die Zeit", uz: "vaqt", exampleDe: "Die Zeit vergeht wie im Flug.", exampleUz: "Vaqt xuddi uchgandek o'tib ketadi." },
  { de: "helfen", uz: "yordam bermoq", exampleDe: "Kann ich Ihnen bei der Übersetzung helfen?", exampleUz: "Sizga tarjimada yordam bera olamanmi?" },
  { de: "freundlich", uz: "do'stona / xushmuomala", exampleDe: "Die Menschen hier sind sehr freundlich.", exampleUz: "Bu yerdagi odamlar juda xushmuomala." },
  { de: "das Wissen", uz: "bilim", exampleDe: "Wissen ist Macht.", exampleUz: "Bilim — kuchdir." },
  { de: "glücklich", uz: "baxtli", exampleDe: "Ich bin so glücklich, Deutsch gelernt zu haben.", exampleUz: "Nemis tilini o'rganganimdan juda baxtliman." },
  { de: "entscheiden", uz: "qaror qilmoq", exampleDe: "Du musst dich schnell entscheiden.", exampleUz: "Sen tezda qaror qabul qilishing kerak." },
  { de: "empfehlen", uz: "tavsiya qilmoq", exampleDe: "Welches deutsche Buch können Sie mir empfehlen?", exampleUz: "Menga qaysi nemischa kitobni tavsiya qila olasiz?" },
  { de: "erklären", uz: "tushuntirmoq", exampleDe: "Der Lehrer kann die Grammatik sehr gut erklären.", exampleUz: "O'qituvchi grammatikani juda yaxshi tushuntira oladi." },
  { de: "gemeinsam", uz: "birgalikda", exampleDe: "Gemeinsam können wir diese Aufgabe lösen.", exampleUz: "Birgalikda biz bu vazifani yecha olamiz." },
  { de: "die Zukunft", uz: "kelajak", exampleDe: "Niemand weiß, was in der Zukunft passiert.", exampleUz: "Kelajakda nima bo'lishini hech kim bilmaydi." },
  { de: "günstig", uz: "arzon / qulay / hamyonbop", exampleDe: "Dieses Angebot ist sehr günstig.", exampleUz: "Bu taklif juda hamyonbop." },
  { de: "die Möglichkeit", uz: "imkoniyat", exampleDe: "Deutschland bietet viele Möglichkeiten für Studenten.", exampleUz: "Germaniya talabalar uchun ko'plab imkoniyatlarni taklif etadi." },
  { de: "vergessen", uz: "unutmoq", exampleDe: "Vergiss nicht, die Hausaufgaben zu machen.", exampleUz: "Uy vazifasini qilishni unutma." },
  { de: "erinnern", uz: "eslamoq / eslatmoq", exampleDe: "Ich erinnere mich gerne an meine Reise nach Berlin.", exampleUz: "Berlinga qilgan sayohatimni mamnuniyat bilan eslayman." },
  { de: "schaffen", uz: "uddalamoq / yaratmoq", exampleDe: "Mach dir keine Sorgen, du wirst es schaffen!", exampleUz: "Xavotir olma, sen buni uddalaysan!" }
];
